[resources]
root = ".local"

[deno]
config = ".runseal/deno.json"
lock = ".runseal/deno.lock"
permissions = [
  "--allow-read",
  "--allow-write=.",
  "--allow-env",
  "--allow-net",
  "--allow-run=git,tea,cargo,sh,deno,plumb,runseal,ectropy",
]

[[injections]]
type = "env"

[injections.vars]
RUNSEAL_REPO_LOCAL_DIR = "resource://"
RUNSEAL_REPO_SECRETS_DIR = "resource://secrets"
RUNSEAL_REPO_TMP_DIR = "resource://tmp"
